apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: employees

spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees

  template:
    metadata:
      labels:
        app: employees

    spec:
      containers:
        - name: application-container
          image: 061186295720.dkr.ecr.us-east-1.amazonaws.com/docker-prod-containers-application:latest
          imagePullPolicy: Always
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: MYSQL_ROOT_PASSWORD
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: "database.database.svc.cluster.local"
            - name: DBUSER
              value: "root"
          ports:
            - containerPort: 8080
