apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: mysql

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: database-container
          image: 061186295720.dkr.ecr.us-east-1.amazonaws.com/docker-containers-database-repo:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
